# Configuration overrides for the 'local' profile
# It helps intellij identify local profile and use it

# This is a broader 'off' switch for all Consul features.
# It's stronger than just disabling discovery.
spring:
  cloud:
    consul:
      enabled: true
      # Use 'localhost' if port-forwarded, or the internal K8s DNS name if running inside the cluster
      host: ${CONSUL_HOST:consul-server.consul.svc.cluster.local}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true

# You can keep this to test or remove it. The application will run on the default 8080 if removed.
server:
  port: 8080